### ISSUE TITLE
Upgrading to a version after 3.20.0 causes issues with hooks

### ISSUE THREAD

**Issue by gitfish** [oclif/core#1013]
It appears that after updating to 3.20.0 none of the custom hooks in my plugin work. I'm guessing it's maybe due to the change in this line: https://github.com/oclif/core/blob/e705c91cae7affca15dc166880eb2b74091e5df5/src/config/config.ts#L557

whereas with version 3.20.0 it was:
https://github.com/oclif/core/blob/8cee1cecaf438daa2c2db964314665e69f91aa36/src/config/config.ts#L550

This change would suggest that I have to update my config as outlined here (to add a target and identifier): https://github.com/oclif/core/pull/945

or I'm probably missing something (such as other code converting the hook entries into this structure).

Our plugin is still built to output commonjs with good old tsc, so not sure whether that's related (and whether we need to stick with a version < 3.21.0 if that's the case) - but I would have thought the code could check the type of the hook entry value to cover off all cases.

Cheers,

**Comment by mdonnalley** [comment]
@gitfish I'm not seeing this on my end - can you create a repository that replicates the issue? Thanks!

**Comment by gitfish** [comment]
Yeah, observing some strange stuff. No issue on my local machine with this, but in one of our devops containers it's presenting the hook config as a string instead of with identifier and target. More digging required on this side.

**Comment by gitfish** [comment]
It's almost like this piece of code is not running (which I don't really see as possible):
https://github.com/oclif/core/blob/7fdc39910d4680e3f112d1c18444b722c4fe609f/src/config/plugin.ts#L89
