### ISSUE TITLE
process.stdout buffering issue

### ISSUE THREAD

**Issue by danielsharvey** [oclif/core#1177]
I am experiencing and issue where lines of the help output are intermitently missed. It appears to be related to buffering/drain on the writes to `process.stdout`.

Specifically, the `stdout`/`stderr` calls to `write()` are not checking the return code, and not waiting for the `drain` event if/when required.

See https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback

https://github.com/oclif/core/blob/f38f8270bafa04cdcb8e6d193b808e099e205864/src/ux/write.ts#L3-L25

I have replaced all calls with synchronous writes as follows and this appears to resolve the issue:

```ts
import {writeSync} from 'node:fs'

...
writeSync(process.stdout.fd, format(...str, ...args) + '\n')
```

Thoughts?

Has anyone else experienced this?

**Comment by mdonnalley** [comment]
@danielsharvey can you create a repro that minimally replicates the issue?

I've tried to reproduce it with this script but haven't had any success:

```typescript
import {ux} from '@oclif/core'

const lines = Array.from({length: 1_000_000}, (_, i) => `Line ${i}`)
const seen = new Set<string>()

// print the lines in parallel
await Promise.all(
  lines.map(async (line) => {
    ux.stdout(line)
    seen.add(line)
  }),
)

// Check that all lines were printed
if (seen.size === lines.length) {
  ux.stdout('All lines were printed')
} else {
  throw new Error('Not all lines were printed')
}
```

**Comment by danielsharvey** [comment]
@mdonnalley Thanks for the prompt response! I will work on an independent test case, but let me share more testing in my codebase.

Importantly, I forgot to mention something looks to be be significant - I'm seeing this occur using Bun. My test case below errors ~70% time with Bun (as per below) but does not occur with Node. Having said that, I think handling "drain" is probably worth addressing.

What I've done is track the output and the `process.stdout.write()` return values.

First, a case when `write()` always returns `true`:
![CleanShot 2024-08-31 at 08 12 22@2x](https://github.com/user-attachments/assets/eef3374c-ac95-4257-8642-e883b3e81cee)

Second, a case when `write()` returned `false` 2 times out of 10:
![CleanShot 2024-08-31 at 08 14 19@2x](https://github.com/user-attachments/assets/3ae5092f-74f6-4ab4-8226-75910bc4281c)

I'm connecting this with the [NodeJS docs](https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback) where they say:

> The return value is true if the internal buffer is less than the highWaterMark configured when the stream was created after admitting chunk. If false is returned, further attempts to write data to the stream should stop until the ['drain'](https://nodejs.org/api/stream.html#event-drain) event is emitted.

My test code is just added to `node_modules/@oclif/core/lib/ux/write.js` as follows:
<details>

<summary>`write.js`</summary>

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.stderr = exports.stdout = void 0;
const node_util_1 = require("node:util");
const node_fs_1 = require("node:fs");

const counts = [0,0];
setTimeout(() => {
  console.log('COUNTS for write [false,true]:', counts);
}, 1000);

const stdout = (str, ...args) => {
    if (!str && args) {
        process.stdout.write((0, node_util_1.format)(...args) + '\n');
        // node_fs_1.writeSync(process.stdout.fd, (0, node_util_1.format)(...args) + '\n');
    }
    else if (!str) {
        process.stdout.write('\n');
        // node_fs_1.writeSync(process.stdout.fd, '\n');
    }
    else if (typeof str === 'string') {
        process.stdout.write((str && (0, node_util_1.format)(str, ...args)) + '\n');
        // node_fs_1.writeSync(process.stdout.fd, (str && (0, node_util_1.format)(str, ...args)) + '\n');
    }
    else {
        // process.stdout.write((0, node_util_1.format)(...str, ...args) + '\n');
        const ok = process.stdout.write((0, node_util_1.format)(...str, ...args) + '\n');
        counts[ok?1:0]++;
        // node_fs_1.writeSync(process.stdout.fd, (0, node_util_1.format)(...str, ...args) + '\n');
    }
};
exports.stdout = stdout;
const stderr = (str, ...args) => {
    if (!str && args) {
        process.stderr.write((0, node_util_1.format)(...args) + '\n');
        // node_fs_1.writeSync(process.stderr.fd, (0, node_util_1.format)(...args) + '\n');
    }
    else if (!str) {
        process.stderr.write('\n');
        // node_fs_1.writeSync(process.stderr.fd, '\n');
    }
    else if (typeof str === 'string') {
        process.stderr.write((str && (0, node_util_1.format)(str, ...args)) + '\n');
        // node_fs_1.writeSync(process.stderr.fd, (str && (0, node_util_1.format)(str, ...args)) + '\n');
    }
    else {
        process.stderr.write((0, node_util_1.format)(...str, ...args) + '\n');
        // node_fs_1.writeSync(process.stderr.fd, (0, node_util_1.format)(...str, ...args) + '\n');
    }
};
exports.stderr = stderr;
```

</details>

**Comment by danielsharvey** [comment]
OK, test case was simpler than I thought. Similar to your test case but just using longer lines.

I'm seeing lots of skipped lines, with typical output from my test:
```
COUNTS for write [false,true]: [ 21, 79 ]
```
i.e. skipping 21 of 100 lines

The issue looks to be not handling the `write()` return code specifying that "further attempts to write data to the stream should stop until the ['drain'](https://nodejs.org/api/stream.html#event-drain) event is emitted".

As above it appears to show up for me using Bun (on my MBP). The issue does not occur for Node in my testing.

My `test.js` code:
```ts
const lines = Array.from({length: 100}, (_, i) => `Line ${i} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer convallis fringilla sollicitudin. Nunc scelerisque neque non ipsum accumsan commodo. In et porttitor eros, ut vestibulum magna. Morbi felis diam, pharetra eu dui non, sollicitudin feugiat nisi. Aliquam cursus malesuada risus, vel luctus leo ornare sed. Morbi condimentum odio id ex facilisis bibendum. Nullam consectetur consectetur viverra. Donec nec ante dui. Integer lacinia facilisis urna vitae feugiat.`)

const counts = [ 0, 0 ];
lines.map((line) => {
  const ok = process.stdout.write(line + '\n');
  counts[ok ? 1:0]++;
});

console.log('COUNTS for write [false,true]:', counts);
```

**Comment by mdonnalley** [comment]
@danielsharvey thanks for investigating it further! I've put up a [PR](https://github.com/oclif/core/pull/1184) to fix it. I think the easiest solution is to use console.log/console.error directly as it seems that those don't have an issue with back pressure. Happy to take suggestions for a better solution though

**Comment by danielsharvey** [comment]
@mdonnalley I think that makes good sense. When I looked at `write.ts` originally I was not sure whether there was a reason I was not aware of for using `process.stdout` rather than console.log/console.error directly).
