### ISSUE TITLE
Can't use esm build in cjs projects

### ISSUE THREAD

**Issue by AllanOricil** [oclif/core#1183]
**Is this a bug with the oclif CLI? Or the oclif framework?**

oclif framework

**Describe the bug**
I'm creating a CLI for a type of project that can only use cjs modules. I built a brand new cli using v4, then I tried to use it and I got this error

![image](https://github.com/user-attachments/assets/e9e5ceb3-7bbe-4f99-901f-6527f763827e)

**To Reproduce**

1. create a new oclif cli called `mycli`
2. run `npm run buil`
3. run `npm link`
4. create a random npm package, and ensure it defaults to `commonjs`
5. run `mycli --help`
6. verify you get this error

```bash
(node:82559) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
    SyntaxError: Cannot use import statement outside a module
```

The `dev.js` build does not work either, even if ts-node is installed globally. It is trying to use the one from the cwd instead of the global one

![image](https://github.com/user-attachments/assets/eb6cfc62-4017-4a6f-9d0d-ee4329580e78)

**Expected behavior**

CLIs built with oclif must also work with commonjs projects, as it won't go away.
Right now, the build scripts Oclif generate are all using esm.

![image](https://github.com/user-attachments/assets/9a1719f0-6749-4659-8bcf-15893c318286)

**Proposed Solution**

At build time, generate `.cjs` and `.mjs` then we can use the one we need based on the type of package we use while developing

**Your Environment (please complete the following information):**

oclif/4.0.3 darwin-arm64 node-v18.18.0

GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Additional context**
It is a CLI to build Node-RED nodes, which only work with commonjs

**Comment by mdonnalley** [comment]
@AllanOricil I'm not sure what your issue might be. The generated ESM CLI does work with CJS packages. I know this because all generated CLIs have a dependency on `@oclif/core`, which is still CJS

**Comment by AllanOricil** [comment]
![image](https://github.com/user-attachments/assets/22c6a885-82e1-45b1-b147-890d6845341d)

**Comment by AllanOricil** [comment]
@mdonnalley what other information do you need?

The issue is not related to the dependencies, but to the type of package that is going to consume the CLI. Look, the evidence below show I can't use my CLI in a common js project

![image](https://github.com/user-attachments/assets/0a4b4293-6c41-44b5-bbaa-c6b28a86b1a7)

**Comment by mdonnalley** [comment]
>The issue is not related to the dependencies, but to the type of package that is going to consume the CLI.

Does that you mean you have a CJS package that will import your ESM CLI? If that's the case, then that's not a limitation that we can do much about in oclif. You do have a couple of options though

- generate a CJS CLI (you can select CommonJS when running `oclif generate`)
- use a dynamic import inside your package to import the CLI, e.g. `await import('mycli')` https://nodejs.org/api/esm.html#import-expressions

**Comment by mdonnalley** [comment]
@AllanOricil This is working for me:

- `oclif generate mycli --yes` to generate ESM cli
- `cd mycli && npm link` 
- create a CJS package in separate directory
- `npm link mycli`
- add a script to package.json: `"test": "mycli hello world"`
- `npm run test` inside CJS package

That being said, I did see the `MODULE_NOT_FOUND` error if you do this from the package directory:

```
../mycli/bin/dev.js hello world
```
But that's not surprising because dev.js looking for ts-node inside the node_modules of the current directory. You can fix that by switching the hashbang in dev.js to `#!/usr/bin/env ts-node`, which will use the global ts-node.

Does that resolve your issue?

**Comment by AllanOricil** [comment]
@mdonnalley will try that and let you know!

**Comment by AllanOricil** [comment]
@mdonnalley changing shebang to `#!/usr/bin/env ts-node` inside ./bin/dev.js worked!

I'm closing this
