### ISSUE TITLE
Library with high vulnerability

### ISSUE THREAD

**Issue by lugogregory** [oclif/core#1231]
I am using its most updated version v-4.0.29, and performing a quality test with Kiuwan, a library with high vulnerability has been detected. It is the library: is-docker@3.0.0, which is a dependency of another library: is-wsl@3.1.0. The vulnerability error it flags is the following:

runc through 1.0-rc6, as used in Docker before 18.09.2 and other products, allows attackers to overwrite the host runc binary (and consequently obtain host root access) by leveraging the ability to execute a command as root within one of these types of containers: (1) a new container with an attacker-controlled image, or (2) an existing container, to which the attacker previously had write access, that can be attached with docker exec. This occurs because of file-descriptor mishandling, related to /proc/self/exe

I propose to carry out a test on these libraries and, as far as possible, update them to avoid high vulnerabilities.

![image](https://github.com/user-attachments/assets/f6122a97-3a86-44e1-8fce-72cc9618fc9d)

**Comment by mdonnalley** [comment]
there's nothing we can do about this until https://github.com/sindresorhus/is-docker/issues/16 is resovled

We have dependabot configured on this repo so we'll pick up the fix as soon as it's released
