### ISSUE TITLE
Introduce deinit hook

### ISSUE THREAD

**Issue by Oscaner** [oclif/core#1263]
**Is your feature request related to a problem? Please describe.**
I have a command to chain sub-commands, and I just want to run final postrun hook, but cannot.

Workflow:
-> [hook] init
-> [hook] prerun
-> [command] main
----> [hook] prerun
----> [command] sub1
----> [hook]  postrun
----> [hook] prerun
----> [command] sub2
----> [hook]  postrun
----> ...
-> [hook]  postrun
-> [hook]  deinit

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mdonnalley** [comment]
@Oscaner why do you need to use a hook?

If you have a command that's chaining other commands, couldn't you just execute your "deinit" code at the end? This is what I'm imagining

```ts
class MyCommand extends Command {
  run() {
   // run "command one"
    this.config.runCommand('command:one')
   // run "command two"
    this.config.runCommand('command:two')
   // final logic here
  }
}
```

**Comment by Oscaner** [comment]
> @Oscaner why do you need to use a hook?
> 
> If you have a command that's chaining other commands, couldn't you just execute your "deinit" code at the end? This is what I'm imagining
> 
> ```ts
> class MyCommand extends Command {
>   run() {
>    // run "command one"
>     await this.config.runCommand('command:one')
>    // run "command two"
>     await this.config.runCommand('command:two')
>    // final logic here
>   }
> }
> ```

For example, I init the Puppeteer browser in "init" hook, and cached the Browser in LRU-cache to globally reuse in every commands.

I don't want remove the Browser in every commands (this is why I cannot use "postrun" hook),
but want remove the Browser when the Chain command finished, or when I just run the independent command (command:one), also want to remove the Browser.

So I need "deinit" hook, just run once when command finished, even if this command contains multiple commands or not.

Thanks.
