### ISSUE TITLE
Remaining Work

### ISSUE THREAD

**Issue by mdonnalley** [oclif/core#146]
As we announced in this [March blog post](https://oclif.io/blog/2021/03/01/introducing-oclif-core), we’re working on v1 of the new @oclif/core library, which we hope to release this summer.

We’ve pinned this issue to keep the community up to date on the remaining work to complete v1 and to update the existing oclif plugins and packages to use core. We’ll update this post as work is completed or new work is added.

## Remaining @oclif/core work

- Allow the option to display suggestions on how to resolve an error [DONE]
- Update the oclif CLI generator to use a single TypeScript template repository [DONE]
    - Archive the following example repositories (to be done as soon as oclif/core is officially released)
        - [example-multi-js](https://github.com/oclif/example-multi-js)
        - [example-multi-ts](https://github.com/oclif/example-multi-ts)
        - [example-plugin-js](https://github.com/oclif/example-plugin-js)
        - [example-plugin-ts](https://github.com/oclif/example-plugin-ts)
        - [example-single-js](https://github.com/oclif/example-single-js)
        - [example-single-ts](https://github.com/oclif/example-single-ts)
        - [githubcli](https://github.com/oclif/githubcli)
        - [kamoji](https://github.com/oclif/kaomoji)
        - [plugin-example](https://github.com/oclif/plugin-example)
- Move old packages to maintenance mode (to be done as soon as oclif/core is officially released)
    - [@oclif/command](https://github.com/oclif/command)
    - [@oclif/config](https://github.com/oclif/config)
    - [@oclif/errors](https://github.com/oclif/errors)
    - [@oclif/parser](https://github.com/oclif/parser)
- Update the [oclif.io](http://oclif.io/) documentation (to be done as soon as oclif/core is officially released)

## Migrating packages and plugins to @oclif/core [DONE]

| Repository                                                                                         | Archive Repo | Determine If Still Requried | Add maitenance notification | Bump Engine to Node 14 | Ensure testing Node 14, 16 & latest & windows | Bump to typescript 4 | Migrate to Core | Major version bump |
|:---------------------------------------------------------------------------------------------------|:------------:|:---------------------------:|:---------------------------:|:----------------------:|:---------------------------------------------:|:--------------------:|:---------------:|:------------------:|
| [@oclif/plugin-autocomplete](https://github.com/oclif/plugin-autocomplete)                         |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-command-snapshot](https://github.com/oclif/plugin-command-snapshot)                 |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-commands](https://github.com/oclif/plugin-commands)                                 |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-help](https://github.com/oclif/plugin-help)                                         |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-interceptor](https://github.com/oclif/plugin-interceptor)                           |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-not-found](https://github.com/oclif/plugin-not-found)                               |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-plugins](https://github.com/oclif/plugin-plugins)                                   |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-update](https://github.com/oclif/plugin-update)                                     |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-warn-if-update-available](https://github.com/oclif/plugin-warn-if-update-available) |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [@oclif/plugin-which](https://github.com/oclif/plugin-which)                                       |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [cli-ux](https://github.com/oclif/cli-ux)                                                          |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [color](https://github.com/oclif/color)                                                            |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [dev-cli](https://github.com/oclif/dev-cli)                                                        |     n/a      |             n/a             |          required           |          n/a           |                      n/a                      |         n/a          |       n/a       |        n/a         |
| [docker](https://github.com/oclif/docker)                                                          |   required   |             n/a             |             n/a             |          n/a           |                      n/a                      |         n/a          |       n/a       |        n/a         |
| [eslint](https://github.com/oclif/eslint)                                                          |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [eslint-config-oclif](https://github.com/oclif/eslint-config-oclif)                                |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [eslint-config-oclif-typescript](https://github.com/oclif/eslint-config-oclif-typescript)          |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [fancy-test](https://github.com/oclif/fancy-test)                                                  |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [fancy-test-nock](https://github.com/oclif/fancy-test-nock)                                        |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [node-linewrap](https://github.com/oclif/node-linewrap)                                            |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [nyc-config](https://github.com/oclif/nyc-config)                                                  |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [oclif](https://github.com/oclif/oclif)                                                            |     n/a      |             n/a             |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [screen](https://github.com/oclif/screen)                                                          |     n/a      |          required           |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [semantic-release](https://github.com/oclif/semantic-release)                                      |     n/a      |          required           |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [test](https://github.com/oclif/test)                                                              |     n/a      |          required           |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [fixpack](https://github.com/oclif/fixpack)                                                        |     n/a      |          required           |             n/a             |        required        |                   required                    |       required       |    required     |      required      |
| [open](https://github.com/oclif/open)                                                              |     n/a      |          required           |             n/a             |        required        |                   required                    |       required       |    required     |      required      |

### [@oclif/plugin-autocomplete](https://github.com/oclif/plugin-autocomplete)

- Update plugin-autocomplete to work with spaced commands
- Update plugin-autocomplete to work on Windows

### [@oclif/plugin-help](https://github.com/oclif/plugin-help)

- Remove old `--help` logic

### [@oclif/plugin-not-found](https://github.com/oclif/plugin-not-found)

- Update plugin-not-found to work with spaced commands

### [@oclif/plugin-update](https://github.com/oclif/plugin-update)

- `promote` should throw an error when no targets are found
- Make `pack`, `promote`, and `upload` commands public
- Remove old s3 logic

**Comment by gingermusketeer** [comment]
I am loving using the oclif framework for building a CLI so far. Is there anything I can help out with in regards to the above migration effort to @oclif/core? 

I made a PR to plugin-autocomplete to do some of the migration work but I am not sure if this is helpful at this stage.

**Comment by dtp263** [comment]
Hey is this still in progress?
