### ISSUE TITLE
@oclif/core has no exported member named 'flags'

### ISSUE THREAD

**Issue by prescience-data** [oclif/core#273]
Receiving this error when following the example in the README doc.

```typescript
import { Command, flags } from "@oclif/core"
```

```
TS2724: '"../../node_modules/@oclif/core/lib"' has no exported member named 'flags'. 
```

## Context
- typescript 4.4.3
- @oclif/core 1.0.2
- node 16
- pnpm 6.19.1

![image](https://user-images.githubusercontent.com/65471523/139044233-8a61f7fd-acf2-4128-8646-101192e8f91d.png)

## Possible solution

https://github.com/oclif/core/blob/main/src/index.ts#L24

Has an export named `Flags`, is this the correct export? If so the main readme might need a quick update.

**Comment by EdNutting** [comment]
The entire sample code didn't work for me in TypeScript. It seems they have refactored some stuff. Here's what worked for me:

```ts
import { Command, Flags } from "@oclif/core";
import { handle } from "@oclif/core/lib/errors/handle";

class LS extends Command {
    static flags = {
        version: Flags.version(),
        help: Flags.help(),
    };

    async run() {
        const { flags: _flags } = await this.parse(LS);

        // TODO
        this.log("Test");
    }

    async _help() {
        this.log("Test help");
    }
}

LS.run().then(undefined, handle);
```

**Comment by strophy** [comment]
The example in the [migration docs](https://github.com/oclif/core/blob/main/MIGRATION.md) is also incorrect, I think? I needed to use `Flags` not `flags`

**Comment by askvortsov1** [comment]
On a similar note, `Topic` is no longer exported directly from "@oclif/core"; it's been moved under the `Interfaces` top level export.

**Comment by eob** [comment]
I just cut #343 to at least fix the REAMDE side of this.

**Comment by RodEsp** [comment]
Fixed by https://github.com/oclif/core/pull/343
