### ISSUE TITLE
Intended approach for env vars?

### ISSUE THREAD

**Issue by Blakeinstein** [oclif/core#324]
I am unsure about the correct way of consuming secrets for some services. I want to provide a github api token to my oclif app, but have not found any documentation on this. I was considering using dotenv (with their `dotenv.config()` syntax) but am unsure if this will work when I generate binaries.

Any help would be awesome

**Comment by mdonnalley** [comment]
@Blakeinstein you should be able to use `dotenv` with the generated binaries. Whoever is using your CLI would just need to have the .env file on their machine

Is the problem that you have a command that depends on a user's github token? If that's the case you could simply require that they set the environment variable in their shell before executing the command. This would be consistent with a lot of existing CLIs - `aws`, for example, requires that you either login or set the appropriate environment variables first.

**Comment by Blakeinstein** [comment]
No I want to ship my own credentials in the binary. Well only the client id for github, which i can just import from some constants. I was more interested in the generic intended way to ship api keys in binaries.
