### ISSUE TITLE
Possibly remove lodash from dependencies

### ISSUE THREAD

**Issue by dsokal** [oclif/core#326]
We've been using `oclif` for https://github.com/expo/eas-cli and it works really great! One thing we try to achieve in our CLI is the minimal package size. I mean we keep an eye on dependencies that we add to our package.json. One of the dependencies we especially try to avoid is `lodash`. It weighs around 5 MB:
```
root@927d4ac7c00b:~/aaa# du -h --max-depth 1 node_modules/ | grep lodash
68K     node_modules/lodash.merge
5.0M    node_modules/lodash
```

Unfortunately, `lodash` is one of the `@oclif/core` dependencies. However, it seems it's not used in many places - https://github.com/oclif/core/search?q=lodash

From what I can see you only use two functions:
- https://github.com/oclif/core/blob/c62f584d82554220b58f4a7d4007ad7a52c870ca/src/config/config.ts#L386
- https://github.com/oclif/core/blob/caaff0b4918ab2e01bc01cad2c0d8158c2fcc1c5/src/help/util.ts#L32

The first one should be pretty straightforward to re-implement. The second is not that easy to replace (but I'm not familiar with the codebase). I also saw this PR https://github.com/oclif/core/commit/caaff0b4918ab2e01bc01cad2c0d8158c2fcc1c5 where you replaced `lodash.template` with `lodash` and I'm quite not sure why because the PR description doesn't say too much about the motivation.

Do you think you could make `oclif` even better and get rid of `lodash` from dependencies? If yes, I'm a volunteer to work on the pull request.

**Comment by RodEsp** [comment]
Hey @dsokal if you'd like to tackle removing Lodash we'd be happy to take a look. However, the PR you referenced was created because `lodash.template` is no longer supported as an npm package and has some critical security issues we needed to address. `lodash` doesn't have the same security problems which is why we switched to it.

**Comment by dsokal** [comment]
Alright, I'll put up a PR soon.
