### ISSUE TITLE
How do I access command help inside command itself? 

### ISSUE THREAD

**Issue by Souvikns** [oclif/core#360]
I want to print the command level help when the command is run, I used to do something like this in the old version 

```ts
import { flags} from '@oclif/command';
import Command from '../base';

export class Config extends Command {
  static description = 'access configs'
  static flags = {
    help: flags.help({char: 'h'})
  }

  async run() {
    await this._help();
  }
}
```

In the new version, I don't think there is `this._help()` function. 

**How can I get the same functionality in the new version?**

**Comment by Pavek** [comment]
I found this solution that works for me:
```
async run() {
      await this.config.runCommand("help", [this.id]);
}
```

From here: https://github.com/oclif/core/blob/main/src/main.ts#L67

**Comment by Souvikns** [comment]
@Pavek what I was trying to do was a bit different but thanks to you I figured it out. Firstly I did not have a help command which is because I am not using the help plugin so this does not work but I did something like this and now it works. 
```ts

    async run(){
        const Help = await loadHelpClass(this.config);
        const help = new Help(this.config)
        help.showHelp(['start', '--help'])
    }


```

**Comment by Pavek** [comment]
@Souvikns Glad it was helpful. You may also get rid of `loadHelpClass` as w/o [Custom Help](https://oclif.io/docs/help_classes#custom-help) it's not very useful: https://github.com/oclif/core/blob/d7067d13c7d80c9e0064455c27ac1ebb6ee53fd2/src/help/util.ts#L27
