### ISSUE TITLE
Lodash error thrown when running `CliUx.ux.open`

### ISSUE THREAD

**Issue by beltingbcg** [oclif/core#365]
Hi, I'm receiving the following error with the lodash module whenever I run `CliUx.ux.open`:

```
/Users/***/Projects/cliux-test/node_modules/@oclif/core/lib/cli-ux/open.js:62
            if (lodash_1.default.isNumber(code) && code > 0) {
                                 ^

TypeError: Cannot read property 'isNumber' of undefined
    at ChildProcess.<anonymous> (/Users/***/Projects/cliux-test/node_modules/@oclif/core/lib/cli-ux/open.js:62:34)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
```

The following code will reproduce the error:

```javascript
import {CliUx} from "@oclif/core";

const run = async () => {
  await CliUx.ux.open("https://www.google.com");
};

run().catch((err) => console.error(err));
```

Please note that the error goes away if I remove the `.default` from the affected line in `open.js` as follows:

```
if (lodash_1.isNumber(code) && code > 0) {
```

I was able to reproduce this on Node versions 12, 14 and 16. Is this a bug or am I importing modules incorrectly?

**Comment by peternhale** [comment]
@beltingbcg Thank you for bringing this to our attention. We will have a look and advise you on what we find.

**Comment by peternhale** [comment]
@beltingbcg This issue has been fixed. Thanks again for bringing it to our attention.

**Comment by beltingbcg** [comment]
@peternhale It works great now, thanks for the quick fix!
