### ISSUE TITLE
Error: resolvePath function can't resolve command file Path (.ts) in development mode.

### ISSUE THREAD

**Issue by m-pizarro** [oclif/core#372]
Hi, we have migrated our oclif CLI to the core version following the [migration guide](https://github.com/oclif/core/blob/main/MIGRATION.md)

**Note:** This error doesn't happen in the previous version

I'm having an error when executing any commands in development mode, in this way for example:

```
  "scripts": {
     "run:init": "NODE_ENV=development ./bin/run init"
  }
```
When I run it using yarn: `yarn run:init`

I'm getting the following error:

```
(node:16497) [MODULE_NOT_FOUND] ModuleLoadError Plugin: @app/cli: [MODULE_NOT_FOUND] require failed to load /source/repos/cli/src/commands/init
module: @oclif/core@1.3.4
task: toCached
plugin: @app/cli
root: /source/repos/cli
```

Reviewing the code I saw that the error occurs in this method: [resolvePath](https://github.com/oclif/core/blob/main/src/module-loader.ts#L132)

![image](https://user-images.githubusercontent.com/64504276/153680205-474cdfc2-ab4f-41b0-a534-67ea9ad913ce.png)

**Debugging error details:**

Input values:
- config.root = /source/repos/cli
- modulePath = lib/commands/init

`line 137  filePath = require.resolve(modulePath)` // it fails and enters to the catch

`line 140 filePath = Config.tsPath(config.root, modulePath)` // filePath = /source/repos/cli/src/commands/init  (It's okay)

In the previous line, It got the path to the typescrtipt files, and since the file has no extension, 
in the line 145, It's append the supported extensions in the s_EXTENSIONS array to try to found it.

![image](https://user-images.githubusercontent.com/64504276/153682003-c14ca27e-e953-4699-8c70-9fa153783bc6.png)

But since the '.ts' extension is not supported it can't find the file.

**It's expected to build the following file path:**

`/source/repos/cli/src/commands/init.ts`

Is that a bug? Or maybe there is something that I'm missing or misconfigured?
I look forward to your comments, thank you very much in advance!

**Comment by typhonrt** [comment]
Hi @m-pizarro. I contributed the code in question ~May of last year as an outside contributor to enable ESM support in oclif v2. Indeed this is a scenario that needs to be evaluated and tests generated. It has been a minute since I have had an opportunity to do anything w/ oclif and presently I don't have time to look into this issue, so perhaps you can take a look at a possible fix / initial analysis. 

What happens if you add `.ts` to `s_EXTENSIONS`? You can modify your local oclif/core copy in `node_modules` to test this. The solution could be as simple as checking if oclif is running in development / TS mode and add `.ts` to s_EXTENSIONS.

**Comment by m-pizarro** [comment]
Hi @typhonrt , thanks for your reply. Yes, I had already done that test, filePath retunrs that for example:

```
isESM: false
filePath: /source/repos/cli/src/commands/init.ts
```

 but then I get the following error:

```
(node:13049) SyntaxError Plugin: @app/cli: Cannot use import statement outside a module
module: @oclif/core@1.3.4
task: toCached
plugin: @app/cli
root: source/repos/cli
 ›   Error: command scan not found
error Command failed with exit code 2.
```

**Comment by typhonrt** [comment]
You might try adding `"type": "module"` to `package.json` just as a test.  Beyond that the error indicates that ts-node is not configured or engaged. You might make sure you've added it as a `devDependency` and perhaps add the shebang to the top of your TS file: `#!/usr/bin/env ts-node`

Are there any instructions available for working with oclif v2 in development / TS mode? 

I can not exactly comment on the state of other parts of Oclif regarding where things are at with other modules besides core that may be involved when Oclif v2 is setup for development / TS mode. I gather what you are running into may need some adjustment for other parts of the infrastructure and would fail any internal tests in a similar manner that you are seeing. At the time I worked on the ESM support only the core module was in a usable state, so the other plugins / modules of Oclif v2 were not finished yet. That being the case I don't have any visibility currently on where things are at in this regard.

**Comment by typhonrt** [comment]
Excellent @m-pizarro! Glad things got resolved. Consider closing this issue when you get a chance.
