### ISSUE TITLE
Aliases with topic Separator set to a space doesn't work. 

### ISSUE THREAD

**Issue by m-pizarro** [oclif/core#389]
Question, I have configured the topicSeparator with spaces.

My aliases look like the following:

`static aliases = ['ls:policy', 'list:policy']`

And the commands in the documentation are generated as expected:

![image](https://user-images.githubusercontent.com/64504276/158886810-1aa1acce-2555-4557-b622-c86ebb147c0d.png)

If I run an alias command without params it works well. That is:  `oex ls policy` or `oex list policy`

But if I try to execute any of the two commands with parameters, for example: `oex ls policy aws`. **I get the error: command `ls:policy:aws` not found.**

Instead this does work by executing the following command: `oex ls:policy aws` (as in oclif v1)

Could this be due to a problem in my configuration or is it a bug in oclif v2?

**Comment by mdonnalley** [comment]
Thanks @m-pizarro I just opened a PR to patch this. I'll hopefully have it merged by today

https://github.com/oclif/core/pull/390

**Comment by m-pizarro** [comment]
Oh great! Thanks @mdonnalley !
