### ISSUE TITLE
Loop when reading hidden prompt from /dev/null 

### ISSUE THREAD

**Issue by joheriks** [oclif/core#405]
A prompt with `{type: "hide"}` option loops forever when input is redirected from `/dev/null`.

To reproduce, create a program like:
```
const {CliUx} = require('@oclif/core')
CliUx.ux.prompt('Enter input', {type: "hide"})
```
Then run it taking stdin from `/dev/null`. Or run `npm i` and then `./prompt.js < /dev/null` in the attached project:
[promptloop.zip](https://github.com/oclif/core/files/8540679/promptloop.zip)

Actual behavior: the prompt loops forever.
Expected behavior: the prompt completes as no data is read (as it does without `{type: "hide"}`).

**Comment by mdonnalley** [comment]
We're planning on removing the `ux` module in the next major version and so we don't plan to address any bugs related to it. We suggest switching to a dedicated prompt library like inquirer
