### ISSUE TITLE
Migrate single command cli to @oclif/core

### ISSUE THREAD

**Issue by felipecrs** [oclif/core#425]
Hi guys, I'm trying to migrate [bindl](https://github.com/felipecrs/bindl), but I'm having a really hard time.

It's a single command CLI (i.e. just calling `bindl` would do the trick), but after following all the advices in the migration guide, it simply does not work.

Am I missing something?

```console
# Before
❯ bin/run
 ›   Error: I was not able to load the configuration file.

# After
❯ bin/dev
Downloads and extracts binaries from compressed packages using a config file

VERSION
  bindl/2.0.0 wsl-x64 node-v16.15.1

USAGE
  $ bindl [COMMAND]
```

**Comment by mdonnalley** [comment]
@felipecrs thanks for brining this up. I've created a #426 to solve this. 

It shouldn't take more than a day or so for the team to review and test the change

**Comment by felipecrs** [comment]
Awesome, thanks a bunch @mdonnalley!
