### ISSUE TITLE
order of enableJsonFlag in code affects whether or not flags are registered

### ISSUE THREAD

**Issue by vidarc** [oclif/core#449]
**Describe the bug**
Specifying enableJsonFlag after flags, causes the flags to not register. This worked fine in the last version I tried, 1.9.5, but has changed in 1.12.0.

**To Reproduce**

will only register the json flag
```javascript
static flags = {
  test: Flags.string()
}
static enableJsonFlag = true
```

will register both flags
```javascript
static enableJsonFlag = true
static flags = {
  test: Flags.string()
}
```

**Comment by mdonnalley** [comment]
@vidarc Thanks for finding this issue. I've got a PR open now to fix it #450
