### ISSUE TITLE
cliUx.ux.flush timeout throws after 10 seconds with `Error: timed out`

### ISSUE THREAD

**Issue by codespool** [oclif/core#453]
**Describe the bug**

When there's a long running process using stdout, this will throw after 10s and break it:
https://github.com/oclif/core/blob/f759fb1710eb1013a48fa04e817d43231553590a/src/cli-ux/index.ts#L21

Before version 1.9.7 it would silently catch it and let it continue:
https://github.com/oclif/core/compare/v1.9.6...v1.9.7

**To Reproduce**

Concrete example:
We're using listr2 task inside a command to spawn process that takes a while to finish (compiling a rust project).
It pipes the stdout into task.stdout().
After 10 seconds, the process exits with an `Error: timed out`
 
**Expected behavior**

The process is not interrupted after 10 seconds.

**Screenshots**
<img width="768" alt="Screenshot 2022-07-25 at 19 21 35" src="https://user-images.githubusercontent.com/4625220/180827447-aeb4b357-9fe1-4a8d-bfad-0ae8da34af50.png">

**Environment (please complete the following information):**

 - MacOS Monterey v12.4
 - zsh 5.7.1 (x86_64-apple-darwin18.2.0) on iTerm2

**Additional context**

https://github.com/AstarNetwork/swanky-cli/blob/master/src/commands/compile/index.ts

**Comment by mdonnalley** [comment]
@codespool The change that went into 1.9.7 actually fixed the flush functionality. The issue in [oclif/oclif#922](https://github.com/oclif/oclif/issues/922) was that we weren't awaiting a promise and fixing `flush` revealed that. You can see the fix here: https://github.com/oclif/oclif/pull/926

I'm assuming that you have a similar issue with your command

**Comment by codespool** [comment]
Ah, I see, so pre 1.9.7 tolerates the buggy code, and that's why it works..
Thanks for clearing it up!

**Comment by codespool** [comment]
Yes, as @mdonnalley hinted, the latest version works when we `await` the `task.run()` promise from listr2.
 
The `promise.race` in the flush implementation gets passed your command and a timeout of 10s, so if you don't `await` for a promise inside your command, and it takes more than 10s to resolve, it will throw that `timed out` error.

So, doesn't matter is it a yeoman generator or something else, as long as you `await` whatever's promise is running in your `Command.run()`

**Comment by azmuelb** [comment]
Ah, that makes sense, I misunderstood the root problem earlier. Maybe our case is a bit special then. We have a command that spawns a _detached_ child process with child_process.spawn, and expects the Node process to exit while the child process continues.

So, I'm not sure if this is still a flaw in oclif not handling that scenario, or if this is just an unusual scenario that should be handled differently on our end.

**Comment by codespool** [comment]
You could wrap spawn in a promise, listen to `exit` event, and resolve when it happens. That should play nicely with oclif/core.
We are using it here:
https://github.com/AstarNetwork/swanky-cli/blob/master/src/commands/compile/index.ts
