### ISSUE TITLE
Allow custom timeouts

### ISSUE THREAD

**Issue by deian** [oclif/core#464]
I'm using the oclif generator (it's great, thanks!), but some of my commands are timing out when using the cli-ux flush implementation:

https://github.com/oclif/core/blob/858b40c32cf0eedab9e183590ab1e07e64f0c8ba/src/cli-ux/index.ts#L132

Any chance you'd be willing to take a PR with optional parameter?

ThankS!

**Comment by john-u** [comment]
This is related to #453 which impacted our project as well. We have a command that opens up an SSE connection for message streaming that was all of the sudden timing out after upgrading to newer versions of @oclif/core. It seems like commands that hit this issue violate an undocumented assumption from oclif: if the Node process is still busy after `Command.run()` resolves, something went wrong in the framework. Any command logic should either complete synchronously or await a Promise before the end of the run context. In this case, the `flush` function had a bug that made it not work and a recent PR fixed this which surfaced the issue for us and others. [Here is an example](https://github.com/SmartThingsCommunity/edge-cli-plugin/pull/54/files#diff-37154dd860420be5b994e7415f4cbfc3f86b1dc41dc72af608e18d3c171504ac) of how we resolved it in our command.

Would it be worth updating the docs to point this out?
