### ISSUE TITLE
Type inference for enum flag

### ISSUE THREAD

**Issue by simonhaenisch** [oclif/core#475]
**Describe the bug**

Basically the same as #469 but for `Flags.enum`.

- Without `multiple` it's inferred as `T` but should be `T | undefined` (unless `required` i guess).
- With `multiple` it's still inferred as `T` but should be `T[] | undefined`.

**Comment by mdonnalley** [comment]
Fixed by https://github.com/oclif/core/commit/799455bbb526b221c806bf8feff6b625dcf50a56

**Comment by simonhaenisch** [comment]
🙏
