### ISSUE TITLE
Dynamic commands stop working with oclif 2 run binaries

### ISSUE THREAD

**Issue by charan678** [oclif/core#479]
**Describe the bug**
I am trying to migrate project from oclif to oclif/core. I am following steps mentioned in this [migration document](https://github.com/oclif/core/blob/main/MIGRATION.md). After implementation of [Update your bin scripts](https://github.com/oclif/core/blob/main/MIGRATION.md#update-your-bin-scripts) step, existing [dynamic commands](https://github.com/oclif/oclif/issues/110) stopped working.
I have implemented dynamic commands similar to this [example](https://github.com/jdxcode/oclif-example-dynamic-commands)
and also this project also showed same result where mydynamiccommand command stopped showing up after replacing run binary file and adding core dependency.

**To Reproduce**
1. use this [example](https://github.com/jdxcode/oclif-example-dynamic-commands)
2. replace binary files with oclif core binaries as mentioned in the document
3. add oclif/core dependency to this project
4. npm install 
5. ./bin/run will stop showing mydynamiccommand

**Expected behavior**
oclif core should support dynamic command as it does for oclif 1

**Environment (please complete the following information):**
 - OS & version: [e.g. MacOS Monterey, Ubuntu 20.04.4 LTS, Windows 10]
 - Shell/terminal & version [e.g. bash-3.2, bash-5.0, zsh 5.8, powershell 7.2.4, cmd.exe, Windows Terminal w/ powershell, etc... ]

**Additional context**

**Comment by mdonnalley** [comment]
@charan678 Thanks for filing the issue.

The example you're following isn't officially supported and we don't currently have bandwidth to prioritize updating it. However, we're always open to contributions if you want to try fixing it yourself.

Let us know if we can help!

**Comment by DanHulton** [comment]
Anyone looking to add dynamic commands back into oclif 2, I think I have it.  Create a new `init` hook like so:
```
import {
  Hook,
  Command,
} from '@oclif/core';

class TestCommand extends Command {
  static id = 'testcommand'

  static summary = 'Test Command';

  async run() {
    this.log('Test command output');
  }
}

const commandLoader: Command.Loadable = {
  strict: false,
  aliases: [],
  args: {},
  flags: {},
  hidden: false,
  id: TestCommand.id,
  async load(): Promise<Command.Class> {
    return TestCommand;
  },
  pluginType: 'user',
};

const hook: Hook<'init'> = async function () {
  (this.config as any).loadCommands({
    commands: [commandLoader],
    topics: [],
  });
};

export default hook;
```
I basically went through the tests and how they dynamically add commands to the test harnesses and worked it into an init hook and it seems to work fairly well.

I imagine this could be done a bit more "officially" but as it stands, it abuses the private `loadCommands` member of `config` a bit, so it's not really clean enough to be just added to the docs.  But if you want to take the chance that further versions of oclif aren't likely to modify that sufficient to break this implementation, that should at least get dynamic commands working again.

**Comment by DanHulton** [comment]
Follow-up to that mention, I packaged up the code for running dynamic commands into a plugin: [oclif-dynamic-commands on npm](https://www.npmjs.com/package/oclif-dynamic-commands).
