### ISSUE TITLE
Hooks are not working properly

### ISSUE THREAD

**Issue by alessandrotesoro** [oclif/core#515]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------

1. When using the `init` hook, you can't exit the CLI by using `this.error` or `this.exit` none of those work.
2. Because of the above, I thought of using the `prerun` hook, this hook doesn't fire at all.
3. Because `prerun` did not work, I tried to use a custom hook, custom hooks aren't working either.

Custom hook code:

```js
import {Hook} from '@oclif/core'

const myhook: Hook<'analytics'> = async function (opts) {
  process.stdout.write(`example custom hook here`)
}

export default myhook
```

Custom command `run` code:

```js
public async run(): Promise<void> {
		const { args, flags } = await this.parse(Tag)

		await this.config.runHook('analytics', {id: 'my_command'})
}
```

package.json

```
"oclif": {
    "bin": "barn2-deployer",
    "dirname": "barn2-deployer",
    "commands": "./dist/commands",
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-plugins"
    ],
    "topicSeparator": " ",
    "topics": {
      "hello": {
        "description": "Say hello to the world and others"
      }
    },
    "hooks": {
      "init": "./dist/hooks/init/verifyPlugin",
      "analytics": "./dist/hooks/analytics/myhook"
    }
  },
```

What is the expected behavior?
------------------------------
Core version: 1.16.4
MacOS Monterey 12.1

**Comment by shrutiburman** [comment]
I'll check it out, thanks!
