### ISSUE TITLE
[observed in v2] cli exits with code 0 even when the command is incorrect

### ISSUE THREAD

**Issue by shrutiburman** [oclif/core#561]
**Describe the bug**
The cli exits with code 0 even when the command is wrong. 
Example: my-cli qwerty would return exit code 0, even though it's meaningless. 

**To Reproduce**
1. Install latest twilio-cli. brew tap twilio/brew && brew install twilio
2. Type command "twilio abc"
3. See error, which is no error. We do have a command_not_found [hook](https://github.com/twilio/twilio-cli/blob/main/src/hooks/command-not-found.js), but looks like the hooks failure is not resulting in any error. 

**Expected behavior**
The command should error out as it was doing earlier. 

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: darwin-x64, node-v16.17.1

**Additional context**
![image](https://user-images.githubusercontent.com/87537688/203357532-ff776beb-9037-4f7d-9985-b4f482b58ceb.png)

**Comment by cristiand391** [comment]
I'll close this as a dup, let's keep the discussion in #515 👍🏼
