### ISSUE TITLE
`./bin/dev` loads from  /src/commands ONLY if `/dist` does not exist

### ISSUE THREAD

**Issue by vladcosorg** [oclif/core#569]
**Describe the bug**
If /dist contains an older version of the build,  running `./bin/dev` will ignore the /src/ and load the older files from /dist
After deleting the /dist folder, everything works fine

**To Reproduce**
1. Run a build `npm run build`
2. Make a change in a command
3. Run the command in dev mode `./bin/dev`
4. The change is not reflected, the command returns the output before the change
5. Remove the `/dist` folder
6. Rerun the command via  `./bin/dev`
7. Now the changes are reflected immediately

**Expected behavior**
When running commands via  `./bin/dev`, they should ignore the `/dist` files 

**Environment (please complete the following information):**
 - OS & version: MacOS Ventura
 - Fish shell
 - Node 16

**Comment by mshanemc** [comment]
@chetzof I don't observe that behavior at all when I try it.

Can you check your ./bin/dev to see if it matches https://github.com/oclif/hello-world/tree/main/bin

**Comment by mshanemc** [comment]
The other thing that may be happening is that there's an compilation error in your changes, and when the TS fails to require, oclif will use the lib if it exists.  After making your change, can you confirm that `build` would have run without error?

**Comment by mdonnalley** [comment]
Closing this since there hasn't been any updates. Please re-open if needed
