### ISSUE TITLE
Topic Flags

### ISSUE THREAD

**Issue by RichiCoder1** [oclif/core#658]
**Is your feature request related to a problem? Please describe.**
It's often useful and help to provide information about shared flags at a topic or root level that are shared between commands.

**Describe the solution you'd like**
Ability to surface top or root level base flags via `help`.

**Describe alternatives you've considered**
Manually overriding the help class to provide this myself.

**Additional context**
I've come from `yargs` which has this built in via [`command modules`](https://github.com/yargs/yargs/blob/main/docs/advanced.md#providing-a-command-module). I understand oclif is a bit different in that commands are effectively seperate entities on all levels and topics are more of "categories" then hard unifies, but it's super helpful to quickly surface basic flags without diving into a specific command.

**Comment by mdonnalley** [comment]
@RichiCoder1 Thanks for the feature request. We don't have the bandwidth at the moment to implement this but you're welcome to submit a PR for it if you desire. 

For what it's worth, this is exactly why we built in the ability to override the help class - it's impossible to know or support all the little nuances that people will want to include in their help output. 

I'm closing this issue for now but feel free to reopen it if you think it's necessary
