### ISSUE TITLE
Print valid command/flags when passing in an invalid value

### ISSUE THREAD

**Issue by cristiand391** [oclif/core#679]
**Is your feature request related to a problem? Please describe.**
When type a wrong command/flag, oclif prints an error suggesting to run `command --help`:

```
➜  plugin-autocomplete git:(cd/powershell) ✗ sf deploy --hehehe
Warning: The top-level deploy command is deprecated. You should use `functions deploy` to deploy functions, and use `project deploy start` to deploy metadata to
 Salesforce orgs.
Error (1): Nonexistent flag: --hehehe
See more help with --help
```

Now I need to run `sf deploy --help`, check the valid flags and re-run the command again.
If the parser knows I'm trying to use an invalid value, why not also print the help text? 
something like this:
```
➜  plugin-autocomplete git:(cd/powershell) ✗ sf deploy --hehehe
Warning: The top-level deploy command is deprecated. You should use `functions deploy` to deploy functions, and use `project deploy start` to deploy metadata to
 Salesforce orgs.
Error (1): unknown flag: --hehe

FLAGS
  --interactive  Force the CLI to prompt for all deployment inputs.

```

**Describe the solution you'd like**
make oclif print valid arg/flags when trying to use an invalid one.

**Describe alternatives you've considered**
make the parser print n args/flags section.

**Additional context**
this is what https://github.com/spf13/cobra/ does:
```
➜  plugin-autocomplete git:(cd/powershell) ✗ gh pr list --hehe
unknown flag: --hehe

Usage:  gh pr list [flags]

Flags:
      --app string        Filter by GitHub App author
  -a, --assignee string   Filter by assignee
  -A, --author string     Filter by author
  -B, --base string       Filter by base branch
  -d, --draft             Filter by draft state
  -H, --head string       Filter by head branch
  -q, --jq expression     Filter JSON output using a jq expression
      --json fields       Output JSON with the specified fields
  -l, --label strings     Filter by label
  -L, --limit int         Maximum number of items to fetch (default 30)
  -S, --search query      Search pull requests with query
  -s, --state string      Filter by state: {open|closed|merged|all} (default "open")
  -t, --template string   Format JSON output using a Go template; see "gh help formatting"
  -w, --web               List pull requests in the web browser
```

**Comment by justinwilaby** [comment]
Hey Oclif team! Is there any movement on this? We're [running into this](https://github.com/heroku/cli/issues/2636) on the heroku-cli.

**Comment by mdonnalley** [comment]
@justinwilaby No movement on it. We had #870 opened to solve this but it raised a lot of design questions that we never answered. What do you have in mind?

**Comment by justinwilaby** [comment]
@mdonnalley - I believe it makes sense to follow exiting idioms. The github CLI approach is familiar to users and comprises a typical UX - I'd roll with that approach. We have observed users append irrelevant flags and args to commands where oclif seems to just eat them by default.  It would be useful to either provide suggestions as described here or throw an error so the CLI author can choose how to act on it.

**Comment by mdonnalley** [comment]
>We have observed users append irrelevant flags and args to commands where oclif seems to just eat them by default. It would be useful to either provide suggestions as described here or throw an error so the CLI author can choose how to act on it.

It should already throw an error if you've on v2 or greater

```
❯ sf version --foo
 ›   Error: Nonexistent flag: --foo
 ›   See more help with --help
```

>The github CLI approach is familiar to users and comprises a typical UX - I'd roll with that approach

So only showing `usage` and `flags`?

```
❯ gh pr status --foo
unknown flag: --foo

Usage:  gh pr status [flags]

Flags:
  -c, --conflict-status   Display the merge conflict status of each pull request
  -q, --jq expression     Filter JSON output using a jq expression
      --json fields       Output JSON with the specified fields
  -t, --template string   Format JSON output using a Go template; see "gh help formatting"
```
