### ISSUE TITLE
Questions about accessibility

### ISSUE THREAD

**Issue by jarrodek** [oclif/core#705]
Hi,

I am a UXer working on MuleSoft's guidelines for CLI plugins. We use Oclif to build our CLI plugins. While I have already published our guidelines internally [internal SF link](https://docs.google.com/document/d/1pkOFDWJKcrxcI4zgCMAtlHLwQydTou-lJJxDsf4bW14/edit) I started looking into a11y of CLI commands. I came across a study (Accessibility of Command Line Interfaces, by Harini Sampath, et al.) that has interesting conclusions. I will be obliged if you can answer my questions about accessibility features of Oclif.

- Does Oclif support translating a table output into other formats (specifically HTML and CSV) - a feature that would be used by visually impaired developers as an alternative output they can work with?
- Does Oclif has any logic that would help creating error messages that can be read by a screen reader in a meaningful way? (this question is about error log formatting, either framework logic or guidelines)
- Does Oclif support inserting links in the `--help` topic? This is to offer a link to the www documentation of the command.
- Does Oclif support accessible progress indicators? This means whether the progress indicator does not use ASCII-art or non-ASCII characters which will be ignored by a screen reader.

Looking forward to the answer.

**Comment by mdonnalley** [comment]
@jarrodek 

> Does Oclif support translating a table output into other formats (specifically HTML and CSV) - a feature that would be used by visually impaired developers as an alternative output they can work with?

Yes for csv but no for html. It's not well documented but there's an [output](https://github.com/oclif/core/blob/main/src/cli-ux/styled/table.ts#L42) option that supports csv, json, and yaml.

> Does Oclif has any logic that would help creating error messages that can be read by a screen reader in a meaningful way? (this question is about error log formatting, either framework logic or guidelines)

No, there's not currently any way to configure error formatting

> Does Oclif support inserting links in the --help topic? This is to offer a link to the www documentation of the command.

Yes, there's a [`url` method on `ux`](https://github.com/oclif/core/blob/main/src/cli-ux/index.ts#L119) that allows you to insert a hyperlink

> Does Oclif support accessible progress indicators? This means whether the progress indicator does not use ASCII-art or non-ASCII characters which will be ignored by a screen reader.

The spinners and progress bars both use non-ASCII characters

**Comment by jarrodek** [comment]
Thanks for the answers!
Our (Mulesoft) teams will continue working on a new internal CLI guidelines. We may come back with some issues. Looking forward to a future cooperation.
