### ISSUE TITLE
Command.parse() method returns undefined flags

### ISSUE THREAD

**Issue by CalemRoelofsSB** [oclif/core#729]
**Describe the bug**
Since version 2.9.0, using `const {flags} = this.parse(MyCommand)` will now return all flags, regardless of whether or not a value has been set for them. 

**To Reproduce**
The following script is a minimal reproducible case for this behaviour:

```javascript
import {Command, Flags} from '@oclif/core'

class LS extends Command {
    static flags = {
        help: Flags.help(),
    }

    async run() {
        const {flags} = await this.parse(LS)
        this.log(flags)
    }
}

LS.run()
```

Running the above using `@oclif/core@2.8.12` will produce the output `{}`
Running that same sample with `@oclif/core@2.9.0` will produce `{ help: undefined }`

**Expected behavior**
Only flags that do not have a value of `undefined` will be included in the `flags` object returned by `parse(Command)`.

**Environment (please complete the following information):**
 - OS & version: MacOS Ventura 13.4
 - Shell/terminal & version: zsh 5.9 (x86_64-apple-darwin22.0)
 - Node.js Version: 18.16.0

**Comment by WillieRuemmele** [comment]
Hi @CalemRoelofsSB - thanks for reporting this and creating a simple reproduction 🏆 

this must've been introduced with https://github.com/oclif/core/pull/726 

did this change cause your commands to break, or was it just a difference?

**Comment by CalemRoelofsSB** [comment]
Hey @WillieRuemmele, appreciate the rapid response (and @mshanemc for already have a PR open)!

> did this change cause your commands to break, or was it just a difference?

This mainly is an issue for commands that perform different actions based on the presence or omission of certain combinations of flags (or a lack of flags completely). 
Just as an example, if you have a command like `mycli file` that can do different operations based on flags like `--delete` or `--update`, it would be standard to have some sort of check like 
```
if (!Object.keys(flags).length) {
 throw new CLIError('Must specify at least one flag!')
}
```
With this new behavior, that check would no longer work as `flags` would now equal `{ delete: undefined, update: undefined }` which would be a breaking change.

We only caught it because of failing tests on a dependabot PR for bumping to 2.9.0
