### ISSUE TITLE
The use of `Array.at` is only on node-16. This breaks @oclif/plugins-plugin@^2.4.8

### ISSUE THREAD

**Issue by shazron** [oclif/core#731]
See: https://github.com/oclif/core/blame/3f4b0f825623448fc18627a4c924fa6cf0b1c470/src/parser/parse.ts#L248
(there should be a total of 6 occurrences of `Array.at` usage in that commit)

`Array.at`:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

@oclif/plugins-plugin@2.x uses @oclif/core@^2.8.2 and still supports node-14.
@oclif/plugins-plugin@3.x does drop node 14 support.

Consider reverting use of `Array.at` at that line (and the other 5 lines) with the equivalent node-14 compatible code:
```
fws.tokens?.slice(-1)?.input
```

If not the release with the use of this `Array.at` syntax should follow semver and be a major version update.

cc @mshanemc

**Comment by shazron** [comment]
Engines say it supports node-14: https://github.com/oclif/core/blob/859370bd3d36b2f6527f51689ae5e9ab3383ccdc/package.json#L85

**Comment by mdonnalley** [comment]
Thanks for posting this @shazron I'm looking into it now
