### ISSUE TITLE
Unable to pass dynamic flags at runtime with strict set to false in command class

### ISSUE THREAD

**Issue by RohitChaturvedi05** [oclif/core#775]
We have one custom `oclif` command for `test` which is internally using `Jest`. It just acts as a wrapper on `jest` and passes all flags and arguments to `jest` directly.

In the previous version of `oclif@1.23.1` we were able to pass the dynamic argument at runtime by setting `strict` to false in the command class. 

```sh
my-command test --watch
```
when we try to do the same with the `oclif@2.11.8` it gives us the following `nonExistentFlags` error although we have set `strict` to false in the command class.

``` sh
  oclif: { exit: 2 },
  code: undefined,
  parse: {
    input: {
      argv: [Array],
      context: [Test],
      '--': undefined,
      flags: [Object],
      args: {},
      strict: false
    },
    output: {
      argv: [Array],
      flags: [Object],
      args: {},
      raw: [],
      metadata: [Object],
      nonExistentFlags: [Array]
    }
  },
  flags: [ '--watch' ]
}
 ›   Error: Nonexistent flag: --watch
 ›   See more help with --help
error Command failed with exit code 2.
```
as you know jest has a lot of flags so it's difficult for us to define each and every flag in its wrapper

**To Reproduce**
1. Create an oclif command.
2. Set strict to false.
3. Run the command with a flag that is not defined in the command
4. See error Nonexistent

**Expected behavior**
As we have set `strict` to `false` in the command class, it should run with a dynamic flag provided at runtime.

**Screenshots**
<img width="693" alt="image" src="https://github.com/oclif/core/assets/17529530/39917c20-ebb0-4360-96ee-dc1570f8261c">

**Environment :**
 - OS & version: MacOS Ventura 13.5
 - Shell/terminal & version: Bash 3.2.57(1)-release (x86_64-apple-darwin22)
 - Node v18.16.0

Thanks in advance.

**Comment by mdonnalley** [comment]
@RohitChaturvedi05 Here's how one option for how you could do this:

```typescript
import {Command, Flags} from '@oclif/core'

const getDynamicFlags = (argv: unknown[]) => {
  return (argv as string[]).filter(a => a.startsWith('-'))
}

export default class Hello extends Command {
  static description = 'Say hello'

  static examples = [
    `$ oex hello friend --from oclif
hello friend from oclif! (./src/commands/hello/index.ts)
`,
  ]

  static flags = {
    from: Flags.string({char: 'f', description: 'Who is saying hello', required: true}),
  }

  static strict = false

  async run(): Promise<void> {
    const {flags, argv} = await this.parse(Hello)
    this.log('flags', flags)
    this.log('dynamic flags', getDynamicFlags(argv))
  }
}
```

```
~/repos/oclif/hello-world (main*) » bin/dev hello --from Oclif -- --watch --foo
flags { from: 'Oclif' }
dynamic flags [ '--watch', '--foo' ]
```

Important things to note in the example are:
1. `strict` is set to false
2. The `argv` array from `this.parse` is used to get everything passed in after the passthrough (`--`)
3. If you also define `args` for your command you'd need to filter those out from `argv` as well

**Comment by RohitChaturvedi05** [comment]
Thanks, @mdonnalley for suggesting this solution.

This comes with some restrictions. Our scripts are used similarly as `react-scripts` which are added in package.json.
`/ /package.json
"test": "my-command test"
}
`
Now to run this command consumer runs them like this `yarn run test` 
Here we can not pass arguments like this `yarn run test -- --watch`  as (--) this is not supported by yarn.

To fix this consumer need to update the package.json, which defeats the purpose of having dynamic flags

`//package.json
"test": "my-command test -- --watch"
`

**Comment by RohitChaturvedi05** [comment]
Thanks @mdonnalley , will consider this solution as we don't have any other alternative.
