### ISSUE TITLE
`bin/dev` does not work as intended after upgrading to @oclif/core to V3

### ISSUE THREAD

**Issue by wataruian** [oclif/core#833]
**Describe the bug**
After upgrading `@oclif/core` to V3, running `bin/dev <command>` does not work as intended and requires a `build` for changes to take effect. It now behaves similarly to `bin/run`.

**To Reproduce**
1. Make changes to a command (`console.log('anything')` will do) without `build`
2. Run using `bin/dev`
3. See the changes won't take effect unless rebuilt

**Expected behavior**
Should behave as `bin/dev` and not be similar to `bin/run`

**Screenshots**
N/A

**Environment (please complete the following information):**
 - MacOS Ventura (ARM64)
 - Node Version: `v18.15.0`
 - Yarn Version: `3.6.3`

**Additional context**
1. `bin/dev` works fine on my previous version `"@oclif/core": "^2.15.0",`
2. I am using Yarn PnP

**Comment by mdonnalley** [comment]
@wataruian I'm not seeing this happen on a newly generated CLI (either from the [CJS template](https://github.com/oclif/hello-world) or the [ESM template](https://github.com/oclif/hello-world-esm))

Can you create a simple repository that replicates the issue? It'd also be helpful if you provided the logs from setting the `DEBUG=config:ts-node` environment variable. That should tell us why it's skipping the compilation step. Thanks!

**Comment by mdonnalley** [comment]
@wataruian Thanks - feel free to reopen the issue if you trace it down to something in oclif
