### ISSUE TITLE
Cache findMatches and commandPermutations

### ISSUE THREAD

**Issue by AllanOricil** [oclif/core#860]
What if [getCommandPermutations](https://github.com/oclif/core/blob/f314ff3bc42cf25be2e0b8512deff72db8739357/src/config/config.ts#L807) result is cached in a file under `~/.config/<CLI>/permutations` so that instead of using CPU we use IO and RAM to load all permutations. 
 => When the computed hash of package.json changes, the command permutations cache is invalidated.

The same could be done with [findMatches](https://github.com/oclif/core/blob/f314ff3bc42cf25be2e0b8512deff72db8739357/src/config/config.ts#L222C10-L222C21). The cache key is the string used to build the matches array. 
 => When the permutations cache is invalidated, findMatches cache should also be invalidated.

Maybe node-persistent-cache can be used to store the cache between command runs in memory and avoid reading files again: https://www.npmjs.com/package/node-persistent-cache

Do you have telemetry data to see the average time, min, max permutations and findMatches takes? If it is a good % of the whole loading time I would try to cache these values.

**Comment by mdonnalley** [comment]
version 3 caches the permutations in the oclif.manifest.json - provided that the plugin/CLI has `flexibleTaxonomy` set in the package.json
