### ISSUE TITLE
Production Dependency Includes Typescript

### ISSUE THREAD

**Issue by c1moore** [oclif/core#878]
**Describe the bug**
It seems that the last few versions of `@oclif/core` has re-introduced TypeScript as a production dependency, significantly increase the bundle size of CLIs using OCLIF.  This appears to be due to the `tsconfck` dependency

```
└─┬ @oclif/core@3.10.8
  └─┬ tsconfck@3.0.0
    └── typescript@5.2.2
```

This seems to increase bundle size by about 10MB depending on compression technique and OS target.

**To Reproduce**
1. Build an OCLIF CLI using the latest version
2. Inspect the bundles

**Expected behavior**
TypeScript is not a production dependency.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS & version: N/A
 - Shell/terminal & version: N/A

**Additional context**
N/A

**Comment by AllanOricil** [comment]
It is weird to see tsconfck depends on ts. If you go to npm, and search for tsconfck you will see it does not have dependencies

https://www.npmjs.com/package/tsconfck

**Comment by c1moore** [comment]
It's marked as a peer dependency, which, if I'm understanding [the docs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies) correctly, means it will be installed with npm v7.

**Comment by AllanOricil** [comment]
you are right. It is a peer dependency

<img width="407" alt="image" src="https://github.com/oclif/core/assets/55927613/594ad778-f104-4961-a94e-23a9e42ff717">

**Comment by c1moore** [comment]
It looks like it's used in production code [here](https://github.com/oclif/core/blob/main/src/util/fs.ts)  I'm not sure the value it's adding over just using `JSON.parse` or using `require` directly.

**Comment by c1moore** [comment]
@AllanOricil Any updates on this?

**Comment by AllanOricil** [comment]
> @AllanOricil Any updates on this?

I can take a look at this next weekend if isn't fixed by Salesforce by than
