### ISSUE TITLE
[BUG]The issue of ux.prompt handling special characters.

### ISSUE THREAD

**Issue by Gourdboy** [oclif/core#927]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

When using ux.prompt to solicit user input, issues arise with special characters such as Chinese, making them unable to be deleted. Using arrow keys results in characters like "^[[a" appearing

What is the expected behavior?
------------------------------
When typing in Chinese, it can be deleted normally, and using the arrow keys allows the cursor to move.

Please mention your oclif and OS version.
iclif 4.0.4  
Apple M1 Pro  Mac os 14.1.1 (23B81)

**Comment by mdonnalley** [comment]
Closing this issue because we've decided to remove the `ux` module in the next major version.
