### ISSUE TITLE
Build failure with `exactOptionalPropertyTypes` enabled

### ISSUE THREAD

**Issue by jhasuraj01** [oclif/core#960]
**Is your feature request related to a problem? Please describe.**

Building the project using this library fails when `exactOptionalPropertyTypes` is enabled in project's `tsconfig.json` unless `skipLibCheck` is also set to `true`. `skipLibCheck` bypasses type checking for third-party libraries, compromising type safety.

**Describe the solution you'd like**
* Add the `exactOptionalPropertyTypes` property to `oclif/core`'s `tsconfig.json`.
* Make any necessary code changes to ensure successful build with this option enabled.

Example [rc/config/plugin.ts#L85](https://github.com/oclif/core/blob/e0c061a2cb2e0602b13bb6354fcf03f35ee9f6e7/src/config/plugin.ts#L85):

<table>
<thead>
<td>From</td>
<td>To</td>
</thead>
<tbody>
<tr>
<td>

```  
{ 
    parent: Plugin | undefined;    
}
```  

</td>
<td>

```
{
    parent?: Plugin;
}
```

</td>
</tr>
</tbody>
</table>

**Additional context**
* This change will improve type safety, leading to fewer potential runtime errors.
* It demonstrates adherence to best practices for TypeScript projects.

I would be happy to come up with a PR or collaborate on a potential solution.

**Comment by WikiRik** [comment]
This is still something I'm interested in

**Comment by WikiRik** [comment]
Just like last month, this still is something I'd like to see. @mdonnalley you marked this as unlikely, while the creator of the issue mentioned that they are willing to come up with a PR. What's holding us back?
